Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-14.0-RELEASE"
  config.vm.hostname = "freebsd"
  config.vm.network "public_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
