---
- hosts: all
  become: yes
  become_user: root

  tasks:

  - name: install dependencies
    apt:
      pkg:
        - curl
      state: latest
      update_cache: true

  - name: create ubuntu user
    ansible.builtin.user:
      name: ubuntu
      group: root
      groups: sudo
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa

  - name: allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'

  - name: copy id_pub.rsa with owner and permissions
    ansible.builtin.copy:
      src: ~/.ssh/id_rsa.pub
      dest: /home/ubuntu/.ssh/authorized_keys
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: disable PermitRootLogin
    lineinfile:
      path: "/etc/ssh/sshd_config"
      line: "PermitRootLogin no"
      state: present
