Vagrant.configure(2) do |config|
    (1..1).each do |i|
        config.vm.define "master" do |master|
            master.vm.box = "ubuntu/jammy64"
            master.vm.hostname = "master"
            master.vm.network "private_network", ip: "192.168.56.1#{i}"
            master.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 2
            end
            master.vm.provision "ansible" do |ansible|
                ansible.playbook = "setup_node.yaml"
            end
        end
    end
end
