Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel9"
  config.vm.hostname = "redhat"
  config.vm.network "public_network", ip: "192.168.0.3"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
