Vagrant.configure("2") do |config|
  config.vm.box = "SLES-15-SP3"
  config.vm.hostname = "suse"
  config.vm.network "public_network", ip: "192.168.0.4"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
