Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/9"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
  config.vm.hostname = "oraclelinux"
  config.vm.network "public_network", ip: "192.168.0.6"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
